name: Setup Root
inputs:
  android_version:
    required: true
  kernel_version:
    required: true
  os_patch_level:
    required: true
  sublevel:
    required: true
  su:
    required: true

runs:
  using: composite
  steps:
    - name: Inject SU
      shell: bash
      run: |
        cd "${{ github.workspace }}/kernel_platform/common"

        case "${{ inputs.su }}" in

          KernelSU)
            echo "Using official KernelSU (main)"
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
            ;;

          SukiSU-Ultra)
            echo "Using SukiSU-Ultra (builtin)"
            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-builtin
            ;;

          KernelSU-Next)
            echo "Using KernelSU-Next (dev)"
            curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/dev/kernel/setup.sh" | bash -s dev
            ;;

          ReSukiSU)
            echo "Using ReSukiSU"
            curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh"
            ;;

          *)
            echo "Unknown SU type: ${{ inputs.su }}"
            exit 1
            ;;
        esac

