name: Build Root-My-Galaxy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 打印根目录文件
        run: ls -la

      - name: 设置JDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 添加gradlew权限
        run: chmod +x gradlew

      - name: 编译Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: 上传APK
        uses: actions/upload-artifact@v4
        with:
          name: Root-My-Galaxy-Debug
          path: 应用程序/build/outputs/apk/debug/*.apk

