name: Build SuKiSU Manager APK

on:
  push:
    paths:
      - 'SukiSU-Ultra/manager/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 配置 JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
          cache: gradle

      - name: 清理预装安卓SDK
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo mkdir -p /usr/local/lib/android/sdk
          sudo chown -R $USER:$USER /usr/local/lib/android

      - name: 安装 Android SDK
        uses: android-actions/setup-android@v3

      - name: 打包Release APK
        working-directory: SukiSU-Ultra/manager
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon --stacktrace

      - name: 上传成品APK
        uses: actions/upload-artifact@v4
        with:
          name: sukisu-manager
          retention-days: 30
          path: SukiSU-Ultra/manager/app/build/outputs/apk/release/*.apk
