name: Build SuKiSU Samsung kernel module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ylarod/ddk-min:android15-6.6-20260313
      options: --privileged

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build kernelsu.ko
      run: |
        cd SukiSU-Ultra/kernel
        CONFIG_KSU=m \
        CONFIG_KSU_SAMSUNG_DEFEX=y \
        CONFIG_KSU_SAMSUNG_KDP=y \
        CONFIG_KSU_SAMSUNG_RKP=y \
        CONFIG_KSU_SAMSUNG_NO_PATCH_TEXT=y \
        CC=clang make
        
        mkdir -p /github/workspace/out
        cp kernelsu.ko /github/workspace/out/android15-6.6_kernelsu-sukisu.ko

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: sukisu-ko
        path: /github/workspace/out/android15-6.6_kernelsu-sukisu.ko
