name: "S25U"
on:
  workflow_dispatch:
    inputs:
      su:
        description: "SU Type"
        required: true
        default: "KernelSU"
        type: choice
        options:
          - KernelSU
          - SukiSU-Ultra
          - KernelSU-Next
          - ReSukiSU

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取B 全覆盖
      - name: Checkout B源码
        uses: actions/checkout@v4
        with:
          repository: sir990928/S25u
          token: ${{ secrets.Yml }}
          fetch-depth: 1

      # 切换分支
      - name: 切换 config-deploy
        run: |
          git fetch origin config-deploy --depth 1
          git checkout origin/config-deploy -- .

      # 关键：就地执行B仓库自带的 Kernel.yml
      - name: 执行B仓库Kernel.yml
        uses: actions/github-script@v7
        with:
          script: |
            const workflow = ".github/workflows/Kernel.yml";
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow,
              ref: context.ref,
              inputs: { su: '${{ github.event.inputs.su }}' }
            });

