name: "S25U"

on:
  workflow_dispatch:
    inputs:
      su:
        description: "SU Type"
        required: true
        default: "KernelSU"
        type: choice
        options:
          - KernelSU
          - SukiSU-Ultra
          - KernelSU-Next
          - ReSukiSU

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout latest main code"
        uses: actions/checkout@v4
        with:
          repository: sir990928/S25u
          token: ${{ secrets.Yml }}
          fetch-depth: 1

      - name: "Overwrite with config-deploy latest code"
        run: |
          git fetch origin config-deploy --depth 1
          git checkout origin/config-deploy -- .

      - name: "Merge large split files"
        uses: ./.github/actions/merge-files

      - name: "Inject SU"
        uses: ./.github/actions/setup-Root
        with:
          su: ${{ github.event.inputs.su }}

      - name: "Configure and inject SUSFS"
        uses: ./.github/actions/setup-susfs
        with:
          android_version: android15
          kernel_version: '6.6'
          os_patch_level: '2025-03-01'
          sublevel: '30'
          apply_ksu_patch: ${{ github.event.inputs.su != '' }}

      - name: "Build kernel"
        run: |
          ./kernel_platform/build/kernel/build.config.sh &
          sleep 2
          yes "" | ./build_kernel_GKI.sh pa3q_chn_openx user sun

      - name: "Generate Zip Name"
        id: zipname
        run: |
          TZ=Asia/Shanghai
          NOW=$(date +"%Y%m%d_%H%M%S")
          SU_NAME=${{ github.event.inputs.su }}
          echo "ZIP_NAME=${SU_NAME}_${NOW}_S25U.zip" >> $GITHUB_ENV

      - name: "Pack kernel zip"
        if: always()
        run: |
          mkdir -p final_artifacts
          git clone --depth 1 -b AnyKernel3 https://github.com/sir990928/-.git ak3_pack

          cp device/qcom/gki-kernel/Image ak3_pack/ || true
          cp device/qcom/gki-kernel/dtbs/dtbo.img ak3_pack/ || true

          mkdir -p ak3_pack/modules/vendor/lib/modules
          find device/qcom/gki-kernel/system_dlkm/lib/modules/ -name "*.ko" -exec cp {} ak3_pack/modules/vendor/lib/modules/ \;

          cd ak3_pack
          zip -r9 ../final_artifacts/${{ env.ZIP_NAME }} .

      - name: "Upload kernel package"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: final_artifacts/${{ env.ZIP_NAME }}

