name: "S25U"

on:
  workflow_dispatch:
    inputs:
      su:
        description: "选择SU类型"
        required: true
        default: "KernelSU"
        type: choice
        options:
          - None
          - KernelSU
          - SukiSU-Ultra
          - KernelSU-Next
          - ReSukiSU

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 仅拉最新单提交，极速检出
        uses: actions/checkout@v4
        with:
          repository: sir990928/S25u
          token: ${{ secrets.Yml }}
          fetch-depth: 1
          submodules: false
          fetch-tags: false

      - name: 🔁 极速拉取 config-deploy 最新覆盖
        run: |
          git fetch origin config-deploy --depth 1 --no-tags
          git checkout --force origin/config-deploy -- .
    
      - name: 碎片合成与授权
        uses: ./.github/actions/merge-files

      - name: 版本号注入
        uses: ./.github/actions/version-patch
        with:
          su: "${{ github.event.inputs.su }}"

      - name: 🧩 注入 SU
        uses: ./.github/actions/setup-Root
        with:
          su: ${{ github.event.inputs.su }}

      - name: 🧩 自动配置并注入 SUSFS
        uses: ./.github/actions/setup-susfs
        with:
          android_version: android15
          kernel_version: '6.6'
          os_patch_level: '2025-03-01'
          sublevel: '30'
          apply_ksu_patch: ${{ github.event.inputs.su != 'None' }}
          
      - name: 编译打包上传全套
        uses: ./.github/actions/build-finish
        with:
          su-type: ${{ github.event.inputs.su }}
