          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-: Build Kernel

构建内核:
: :

名称:
  构建:
    流道: ubuntu-latest
    步骤:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt update && sudo apt install -y bc bison flex gcc-aarch64-linux-gnu libssl-dev make zip

      - name: Download your zip package
        run: wget -O files.zip "https://3004.filemail.com/api/file/get?compressedfilekey=mFzHcD7uQxqiELj5hREADDk799vJ1AYPfpDs-uWemg"

      - name: Unzip all
        run: unzip files.zip -d .

      - name: Extract kernel
        run: mkdir kernel && tar -xf *.tar.gz -C kernel --strip-components=1 2>/dev/null || true

      - name: Extract toolchain
        运行: mkdir toolchain && ls | grep toolchain | xargs -I  mkdir 工具链 &&&ls | grep 工具链 | xargs -I } tar -xf {} -C toolchain --strip-components=1 2>/dev/null || true

      - name: Build kernel
        运行: |
          cd kernel
          make ARCH=arm64 CROSS_COMPILE=../toolchain/bin/aarch64-linux-gnu- defconfig
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=./toolchain/bin/aarch64-linux-gnu-

      - name: Make flashable zip
        运行: |
          CD 内核
          zip kernel.zip arch/arm64/boot/Image* arch/arm64/boot/dtbo.img

      - uses: actions/upload-artifact@v4
        与:
          name: kernel-flashable
          path: kernel/kernel.zip
