name: Build CVE Payload AYA1
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.Yml }}
          persist-credentials: false

      - name: 安装基础工具
        run: |
          sudo apt update
          sudo apt install -y make wget unzip

      - name: 解压NDK r27
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27-linux.zip
          unzip android-ndk-r27-linux.zip
          echo "$PWD/android-ndk-r27/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: 进入项目目录编译release载荷
        run: |
          cd Root-My-Galaxy-Payloads-main
          make clean
          make TARGET=pa3q-S9380ZHU1AYA1 TARGET_CC=aarch64-linux-android35-clang release

      - name: 复制so到artifacts目录（覆盖旧文件）
        run: |
          cd Root-My-Galaxy-Payloads-main
          SRC_SO="makelife/build/pa3q-S9380ZHU1AYA1/cve-2026-43499-app.release.so"
          DST_FOLDER="artifacts/pa3q-S9380ZHU1AYA1"
          DST_SO="${DST_FOLDER}/cve-2026-43499-app.so"
          mkdir -p ${DST_FOLDER}
          cp -v ${SRC_SO} ${DST_SO}

      - name: Git推送更新文件
        run: |
          cd Root-My-Galaxy-Payloads-main
          git config --global user.name "CI Builder"
          git config --global user.email "ci@localhost"
          git remote set-url origin https://${{ secrets.Yml }}@github.com/${{ github.repository }}.git
          git add artifacts/pa3q-S9380ZHU1AYA1/cve-2026-43499-app.so
          if git commit -m "CI: auto build update pa3q-S9380ZHU1AYA1 payload";then
            git push origin HEAD:main
            echo "✅ 新版本so已覆盖推送仓库"
          else
            echo "ℹ️ 文件无变更，跳过提交"
          fi

